# Replica count
# Image, both name and tag
# Service type and port

## @param replicaCount Number of Nginx replicas to deploy
replicaCount: 3

## Settings for NGINX image
##
## @param image.name Nginx image name to use
## @param image.tag Nginx image tag to use
image:
    name: nginx
    tag: "1.27.5"

## NGINX container port
##
## @param containerPorts.http Port number for the Nginx container
containerPorts:
    http: 80

## Setting for NGINX service
## 
## @param service.enabled Whether to deploy the service altogether or not
## @param service.type Type of Kubernetes service to create (ClusterIP, NodePort, LoadBalancer)
## @param service.port Port number for the Nginx service
service:
    enabled: true
    type: ClusterIP
    port: 80