## @param customName allows to set a custom resource name for the K8s resources in the chart.
##        Defaults to {{ .Release.Name }}-{{ .Chart.Name }}
customName: 'my-custom-release'

# Replica count
# Image, both name and tag
# Service type and port

## @param replicaCount Number of Nginx replicas to deploy
replicaCount: 3

## Settings for NGINX image
##
## @param image.name Nginx image name to use
## @param image.tag Nginx image tag to use
image:
  name: nginx
  tag: "1.27.5"

## NGINX container port
##
## @param containerPorts.http Port number for the Nginx container
containerPorts:
  http: 80

## Setting for NGINX services
## services is a map with the following schema
## 
## @param services[*].type Type of Kubernetes service to create (ClusterIP, NodePort, LoadBalancer)
## @param services[*].port Port number for the Nginx service
services:
  svc1:
    type: ClusterIP
    port: 80
  svc2:
    type: NodePort
    port: 30007