{{- range $key, $svc := .Values.services | default dict }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "templating-deep-dive.fullname" $ }}-{{ $key }}
  labels:
    {{- include "templating-deep-dive.selectorLabels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  selector:
    {{- include "templating-deep-dive.selectorLabels" $ | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ include "templating-deep-dive.validators.portRange" .port }}
      targetPort: {{ $.Values.containerPorts.http }}
{{ end }}
